// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGOdJoZr1_WoHiJdFMP_UmWYlELzD5_1k',
    appId: '1:856063449095:web:35a4c69f3a3726d3fcf2a2',
    messagingSenderId: '856063449095',
    projectId: 'findkost-4f709',
    authDomain: 'findkost-4f709.firebaseapp.com',
    storageBucket: 'findkost-4f709.firebasestorage.app',
    measurementId: 'G-MT433LED75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbvpJVR1z6w9BB9JJikem1IOwqSRjyrE',
    appId: '1:856063449095:android:da2a2f0d236afa77fcf2a2',
    messagingSenderId: '856063449095',
    projectId: 'findkost-4f709',
    storageBucket: 'findkost-4f709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQTg8ejhrra2rX4XjuCx5VTLvOCu-ed8',
    appId: '1:856063449095:ios:6e93abccb4f873c2fcf2a2',
    messagingSenderId: '856063449095',
    projectId: 'findkost-4f709',
    storageBucket: 'findkost-4f709.firebasestorage.app',
    androidClientId: '856063449095-ajpevfi7khn0dtkfjh3m3lk5schslq00.apps.googleusercontent.com',
    iosClientId: '856063449095-ic8fok2ghppvtnebelg2s79dq4c7u43u.apps.googleusercontent.com',
    iosBundleId: 'com.example.findkost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnQTg8ejhrra2rX4XjuCx5VTLvOCu-ed8',
    appId: '1:856063449095:ios:6e93abccb4f873c2fcf2a2',
    messagingSenderId: '856063449095',
    projectId: 'findkost-4f709',
    storageBucket: 'findkost-4f709.firebasestorage.app',
    androidClientId: '856063449095-ajpevfi7khn0dtkfjh3m3lk5schslq00.apps.googleusercontent.com',
    iosClientId: '856063449095-ic8fok2ghppvtnebelg2s79dq4c7u43u.apps.googleusercontent.com',
    iosBundleId: 'com.example.findkost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGOdJoZr1_WoHiJdFMP_UmWYlELzD5_1k',
    appId: '1:856063449095:web:2742d9edc0f9ba10fcf2a2',
    messagingSenderId: '856063449095',
    projectId: 'findkost-4f709',
    authDomain: 'findkost-4f709.firebaseapp.com',
    storageBucket: 'findkost-4f709.firebasestorage.app',
    measurementId: 'G-G2FCZS8LRN',
  );
}
